tags:
  productsNetworkingOffline: false
  discountsNetworkingOffline: false
  discounts-green: true

discountsNetworkingOnline:
  router:
    enabled: false

productsNetworkingOnline:
  router:
    enabled: false

domain: change_me

global:
  istio:
    enabled: true
    rollouts:
      enabled: false
    productsblueWeight: 100
    productsgreenWeight: 0
    discountsblueWeight: 100
    discountsgreenWeight: 0


products-green:
  quarkus-base:
    replicaCount: 0
    image:
      tag: v1.1.1
  mode: online
products-blue:
  quarkus-base:
    replicaCount: 4
    image:
      tag: v1.0.1
  mode: online

discounts-blue:
  quarkus-base:
    replicaCount: 2
    image:
      tag: v1.0.1
  mode: online
discounts-green:
  quarkus-base:
    replicaCount: 1
    image:
      tag: v1.0.1
  mode: online

