tags:
  discounts-green: false
  products-green: false

discounts-blue:
  mode: online
  quarkus-base:
    image:
      tag: v1.0.1
    version: none
    rollouts:
      enabled: true
      blueGreen:
        enabled: true
        activeService: "discounts-umbrella-online"
        previewService: "discounts-umbrella-offline"
    
products-blue:
  mode: online
  quarkus-base:
    image:
      tag: v1.0.1
    replicaCount: 2
    version: none
    rollouts:
      enabled: true
      blueGreen:
        enabled: true
        activeService: "products-umbrella-online"
        previewService: "products-umbrella-offline"

global:
  namespace: test
  #needed for rollouts analysis









