tags:
  discounts-green: false
  products-green: false

global:
  namespace: test
  #needed for rollouts analysis
  prometheusAddress: https://prometheus-user-workload.openshift-user-workload-monitoring.svc.cluster.local:9091

discounts-blue:
  mode: online
  quarkus-base:
    fullnameOverride: "discounts"
    image:
      tag: v1.0.1
    version: none
    rollouts:
      enabled: true
      analysis:
        query: sum(http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200", service="products-umbrella-online",response_code!~"5.*", uri="/products",})
      canary:
        steps:
          - setWeight: 50
          - pause:
              duration: 1m
  fullnameOverride: "discounts"
  
products-blue:
  mode: online
  quarkus-base:
    image:
      tag: v1.0.1
    replicaCount: 2
    fullnameOverride: "products"
    version: none
    rollouts:
      enabled: true
      analysis:
        query: sum(http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200", service="products-umbrella-online",response_code!~"5.*", uri="/products",})
      canary:
        steps:
          - setWeight: 10
          - pause:
              duration: 30s
          - setWeight: 50
          - pause:
              duration: 30s
  fullnameOverride: "products"









