tags:
  discounts-green: false
  products-green: false

discounts-blue:
  fullnameOverride: "discounts"
  image:
    tag: v1.0.1
  version: none
  rollouts:
    enabled: true
    analysisService: "discounts-umbrella-offline"
    canary:
      stableService: "discounts-umbrella-online"
      canaryService: "discounts-umbrella-offline"
      steps:
        - setWeight: 50
        - pause:
            duration: 1m
    
products-blue:
  mode: online
  image:
    tag: v1.0.1
  version: none
  replicaCount: 4
  fullnameOverride: "products"
  rollouts:
    enabled: true
    analysisService: "products-umbrella-offline"
    canary:
      stableService: "products-umbrella-online"
      canaryService: "products-umbrella-offline"
      steps:
        - setWeight: 25
        - pause:
            duration: 30s
        - setWeight: 50
        - pause:
            duration: 30s
global:
  namespace: test
  #needed for rollouts analysis









