{{- if .Values.argorollouts.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: argo-rollouts
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml'
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
{{ end }}