{{- if .Values.argo-rollouts.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
  labels:
     argocd.argoproj.io/managed-by: openshift-gitops
spec:
  finalizers:
  - kubernetes
{{ end }}