{{- if .Values.argo-rollouts.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: RolloutManager
metadata:
  name: argo-rollout
  namespace: argo-rollouts
spec:
  extraCommandArgs:
    - '--namespaced=false'
{{ end }}
