{{- range $user := $.Values.users }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $user }}
spec:
  description: {{ $user }} 
  sourceRepos:
  - '*'
  destinations:
{{- range $namespace := $.Values.namespaces }}
    - namespace: {{ $user }}-{{ $namespace }}
      server: https://kubernetes.default.svc
{{- end }}  
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - description: Group to developers to deploy on DEV environment
      groups:
        - {{ $user }}
      name: developers
      policies:
        - >-
          p, proj:{{ $user }}:developers, applications, *,
          {{ $user }}/*, allow
        - >-
          p, proj:{{ $user }}:developers, applicationsets, *,
          {{ $user }}/*, allow
        - >-
          p, proj:{{ $user }}:developers, repositories, *, *, allow
        - >-
          p, proj:{{ $user }}:developers, logs, get, *, allow
---
{{- end }}