{{- range $user := $.Values.users }}
{{- $var_user := $user }}
{{- range $namespace := $.Values.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $var_user }}-{{ $namespace }}
  labels:
     argocd.argoproj.io/managed-by: openshift-gitops
spec:
  finalizers:
  - kubernetes
---
{{- end }}
{{- end }}