{{- with .Values.users }}
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  rbac:
    defaultPolicy: 'role:admin'
    policy: 'g, system:cluster-admins, role:admin'
    scopes: '[groups]'
{{- end }}