apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-configuration
spec:
  generators:
  - list:
      elements:
      - namespace: gitops-pre
      - namespace: gitops-prod
  template:
    metadata:
      name: '{{namespace}}-cluster-configuration'
      namespace: openshift-gitops
    spec:
      destination:
        name: ''
        namespace: openshift-gitops
        server: 'https://kubernetes.default.svc'
      source:
        path: gitops/cluster-config
        repoURL: 'https://github.com/davidseve/cloud-native-deployment-strategies.git'
        targetRevision: multienv
        helm:
          parameters:
            - name: "github.token"
              value: "changeme_token"
            - name: "github.user"
              value: "changeme_user"
            - name: "github.mail"
              value: "changeme_mail"
            - name: "github.repository"
              value: "changeme_repository"
            - name: "bluegreen.valuesyaml"
              value: 'values/envs/values-{{namespace}}.yaml'
            - name: "namespace"
              value: '{{namespace}}'
      project: default
      syncPolicy:
        automated:
          prune: false
          selfHeal: false 