{{- if .Values.istio.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  # annotations:
  #   argocd.argoproj.io/sync-wave: "0"
  name: istio-system
  labels:
     argocd.argoproj.io/managed-by: openshift-gitops
spec:
  finalizers:
  - kubernetes
{{ end }}