{{- if .Values.istio.enabled }}
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "21"
spec:
  runtime:
    components:
      pilot:
        deployment:
          replicas: 3
  tracing:
    sampling: 10000
    type: Jaeger
  gateways:
    enabled: true
    egress:
      enabled: true
      runtime:
        deployment:
          replicas: 3
    ingress:
      enabled: true
      runtime:
        deployment:
          replicas: 3
    openshiftRoute:
      enabled: false
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  version: v2.4
  telemetry:
    type: Istiod
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus-backdoor
spec:
  ports:
    - name: http-prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
  selector:
    app: prometheus 
{{ end }}