{{- if .Values.pipeline.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: blue-green-github-token
  namespace: gitops
  annotations:
    tekton.dev/git-0: 'https://github.com/{{ .Values.github.user }}'
    argocd.argoproj.io/sync-wave: "-5"
data:
  password: {{ .Values.github.token | b64enc | quote }}
  username: {{ .Values.github.user | b64enc | quote }}
type: kubernetes.io/basic-auth
{{ end }}