{{- if .Values.github.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: github-token
  namespace: {{ .Values.namespace }}
  annotations:
    tekton.dev/git-0: 'https://github.com/{{ .Values.github.user }}'
data:
  password: {{ .Values.github.token | b64enc | quote }}
  username: {{ .Values.github.user | b64enc | quote }}
type: kubernetes.io/basic-auth
---
#For github-open-pr
kind: Secret
apiVersion: v1
metadata:
  name: github
  namespace: {{ .Values.namespace }}
data:
  token: {{ .Values.github.token | b64enc | quote }}
{{ end }}