apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: blue-green-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  members:
    - blue-green-gitops