{{- if .Values.rollouts.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "quarkus.fullname" . }}-analysis-template
  labels:
    {{- include "quarkus.labels" . | nindent 4 }}
spec:
  metrics:
  - name: {{ include "quarkus.fullname" . }}-webmetric
    interval: 10s
    successCondition: len(result) == 0 || result[0] >= 0.95
    failureLimit: 2
    provider:
      prometheus:
        address: {{ .Values.global.prometheusAddress }}
        query: |
          {{ .Values.rollouts.analysis.query | indent 10 }}
{{- end }}