{{- if .Values.rollouts.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "quarkus.fullname" . }}-analysis-template
  labels:
    {{- include "quarkus.labels" . | nindent 4 }}
spec:
  metrics:
  - name: {{ include "quarkus.fullname" . }}-webmetric
    interval: 20s
    count: 5
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: {{ .Values.global.prometheusAddress }}
        query: |
          sum(irate(
            http_server_requests_seconds_count{method="GET",status!~"5.*",service="{{ .Values.rollouts.analysisService  }}"}[20s]
          )) /
          sum(irate(
            http_server_requests_seconds_count{method="GET",service="{{ .Values.rollouts.analysisService   }}"}[20s]
          ))
{{- end }}