{{- if .Values.rollouts.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "quarkus.fullname" . }}-analysis-template
  labels:
    {{- include "quarkus.labels" . | nindent 4 }}
spec:
  metrics:
{{- if .Values.rollouts.blueGreen.enabled }}
  - name: {{ include "quarkus.fullname" . }}-webmetric
    successCondition: result == 'UP'
    provider:
      web:
        url: "http://{{ .Values.rollouts.blueGreen.previewService }}.{{ .Values.global.namespace }}.svc.cluster.local:8080/q/health/ready"
        jsonPath: "{$.status}"
{{- end }}
{{- with .Values.rollouts.canary }}
  - name: {{ include "quarkus.fullname" $ }}-prometheus-metric
    interval: 10s
    successCondition: len(result) == 0 || result[0] >= 0.95
    failureLimit: 2
    provider:
      prometheus:
        address: {{ $.Values.global.prometheusAddress }}
        query: |
          {{ $.Values.rollouts.analysis.query | indent 10 }}
{{- end }}
{{- end }}