{{- if .Values.pipeline.applications.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: dseveria-poc-applications-ci-pull-secret
  annotations:
    tekton.dev/docker-0=https://quay.io/dseveria
data:
  .dockerconfigjson: {{- if .Values.pipeline.applications.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
{{ end }}