{{- if .Values.pipeline.enabled }}
{{- range $user := $.Values.users }}
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ $user }}-continuous-delivery
  generateName: {{ $user }}-link-github-token-cd-
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: link-github-token
        image: quay.io/openshift/origin-cli:4.7
        command:
          - "oc"
          - "secrets"
          - "link"
          - "pipeline"
          - "github-token"
          - "-n"
          - "{{ $user }}-continuous-delivery"
      restartPolicy: Never
  backoffLimit: 10
{{- end }}
{{- end }}