{{- if .Values.pipeline.enabled }}
{{- range $user := $.Values.users }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $user }}-continuous-delivery
  labels:
     argocd.argoproj.io/managed-by: openshift-gitops
spec:
  finalizers:
  - kubernetes
---
#Add user to namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $user }}-namespace-continuous-delivery
  namespace: {{ $user }}-continuous-delivery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: Group
  name: {{ $user }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}