{{- range $user := $.Values.users }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $user }}-gitops-edit-pipeline
  namespace: {{ $user }}-continuous-delivery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: {{ $user }}-continuous-delivery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $user }}-gitops-admin
  namespace: {{ $user }}-continuous-delivery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ $user }}-continuous-delivery
{{- $var_user := $user }}
{{- range $namespace := $.Values.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $var_user }}-{{ $namespace }}-gitops-edit-pipeline
  namespace: {{ $var_user }}-{{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: {{ $var_user }}-continuous-delivery
{{- end }}
{{- end }}