{{- range $user := $.Values.users }}
{{- $var_user := $user }}
{{- range $namespace := $.Values.namespaces }}
---
kind: Secret
apiVersion: v1
metadata:
  name: github-token
  namespace: {{ $var_user }}-{{ $namespace }}
  annotations:
    tekton.dev/git-0: 'https://github.com/{{ .Values.github.user }}'
data:
  password: {{ .Values.github.token | b64enc | quote }}
  username: {{ .Values.github.user | b64enc | quote }}
type: kubernetes.io/basic-auth
---
#For github-open-pr
kind: Secret
apiVersion: v1
metadata:
  name: github
  namespace: {{ $var_user }}-{{ $namespace }}
data:
  token: {{ .Values.github.token | b64enc | quote }}
{{- end }}
{{- end }}