{{- if .Values.pipeline.enabled }}
{{- range $user := $.Values.users }}
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: shop-e2e-test
  namespace: {{ $user }}-continuous-delivery
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  params:
  - name: TARGET_VERSION
  - name: JQ_PATH
  - name: LABEL
  steps:
  - name: set-results
    image: badouralix/curl-jq
    script: |
      version="none"
      cat $(workspaces.source.path)/url
      while [[ "$version" != "$(params.TARGET_VERSION)" ]]
      do
        sleep 5
        curl $(cat $(workspaces.source.path)/url) | jq -r '$(params.JQ_PATH)' > metadata
        cat metadata
        version=$(jq -r '$(params.LABEL)' metadata)
        echo $version
      done
  workspaces:
  - name: source
{{- end }}
{{- end }}
