tags:
  discounts-green: false
  products-green: false

discounts-blue:
  fullnameOverride: "discounts"
  image:
    tag: v1.0.1
  rollouts:
    enabled: true
    canary:
      steps:
        - setWeight: 50
        - pause:
            duration: 1m
    
products-blue:
  mode: online
  image:
    tag: v1.1.1
  replicaCount: 4
  fullnameOverride: "products"
  rollouts:
    enabled: true
    canary:
      steps:
        - setWeight: 50
        - pause:
            duration: 1m

global:
  namespace: test
  #needed for rollouts analysis









