apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: shop-products-new-version-
spec:
  #serviceAccountName: pipelines-github-token
  pipelineRef:
    name: pipeline-blue-green    
  params:
  - name: APP
    value: products
  - name: NEW_IMAGE_TAG
    value: "v1.1.1"
  - name: STEP
    value: "new-version"
  - name: SOURCE_GIT_REVISION
    value: blue-green
  - name: GIT_USER_NAME
    value: davidseve
  - name: GIT_USER_EMAIL
    value: davidseve16@gmail.com
  workspaces:
  - name: app-source
    persistentVolumeClaim:
      claimName: workspace-pvc-shop-cd-new-version