apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: shop-products-switch-
spec:
  pipelineRef:
    name: pipeline-blue-green    
  params:
  - name: APP
    value: products
  - name: REPLICA_COUNT
    value: "2"
  - name: STEP
    value: "switch"
  - name: SOURCE_GIT_REVISION
    value: blue-green
  - name: GIT_USER_NAME
    value: davidseve
  - name: GIT_USER_EMAIL
    value: davidseve16@gmail.com
  workspaces:
  - name: app-source
    persistentVolumeClaim:
      claimName: workspace-pvc-shop-cd-new-version