apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-ci
  namespace: blue-green-gitops
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ci/pipeline
    repoURL: 'https://github.com/davidseve/poc-quarkus-applications.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default