apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-configuration
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: gitops/cluster-config
    repoURL: 'https://github.com/davidseve/cloud-native-deployment-strategies.git'
    targetRevision: HEAD
    helm:
     parameters:
      - name: "istio.enabled"
        value: "true"
      - name: "bluegreen.enabled"
        value: "false"
      - name: "pipeline.enabled"
        value: "false"
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false