apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: argo-rollouts
    server: 'https://kubernetes.default.svc'
  source:
    path: gitops/argo-rollouts
    repoURL: 'https://github.com/davidseve/cloud-native-deployment-strategies.git'
    targetRevision: rollouts
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false