apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pipelines
spec:
  generators:
  - list:
      elements:
      - name: ci
        path: ci/pipeline
        repoURL: https://github.com/davidseve/poc-quarkus-applications.git
        targetRevision: HEAD
      - name: blue-green
        path: pipelines
        repoURL: https://github.com/davidseve/cloud-native-blue-green.git
        targetRevision: HEAD
  template:
    metadata:
      name: 'pipeline-{{name}}'
    spec:
      destination:
        name: ''
        namespace: blue-green-gitops
        server: 'https://kubernetes.default.svc'
      source:
        path: '{{path}}'
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        directory:
          recurse: true
      project: default
      syncPolicy:
        automated:
          prune: false
          selfHeal: false