apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: blue-green-gitops-role-binding
  namespace: blue-green-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: argocd-cluster-argocd-application-controller
  namespace: openshift-gitops