apiVersion: v1
kind: Namespace
metadata:
  name: blue-green-gitops
spec:
  finalizers:
  - kubernetes
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: blue-green-gitops-role-binding
  namespace: blue-green-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: argocd-cluster-argocd-application-controller
  namespace: openshift-gitops
---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: poc-pipelines
# spec:
#   finalizers:
#   - kubernetes
# ---