{{- if .Values.argorollouts.enabled }}

---
apiVersion: v1
kind: Secret
metadata:
  name: istio-helm-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://argoproj.github.io/argo-helm
  name: argo-helm
  type: helm
{{ end }}