apiVersion: v1
kind: Namespace
metadata:
  name: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  labels:
     argocd.argoproj.io/managed-by: openshift-gitops
spec:
  finalizers:
  - kubernetes