apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: link-secret-github
  namespace: gitops
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  taskRef:
      name: openshift-client
  params:
  - name: SCRIPT
    value: |
        oc secrets link pipeline github-token -n gitops